---

- hosts: all
  sudo: True
  tasks:
    setup:
      filter: '*'

- hosts: all
  sudo: True
  vars:
    base: /home/vagrant/local
    build: /home/vagrant/scratch
    local_env:
      PATH: "/home/vagrant/local/bin:{{ansible_env.PATH}}"
  tasks:

    ## Directories
    - name: Make directories
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - "{{ base }}"
        - "{{ build }}"
        - "{{ base }}/man/man1"
        - "{{ base }}/lib"
        - "{{ base }}/include"

    ## C and its friends
    - name: Install required packages
      yum:
        name: autoconf,automake,gcc,gcc-c++,git,libtool

    ## cmake
    - name: Get cmake
      get_url:
        dest: "{{ build }}/cmake-3.3.1.tar.gz"
        url: http://www.cmake.org/files/v3.3/cmake-3.3.1.tar.gz
    - name: Unpack cmake
      command: tar -zxf {{ build }}/cmake-3.3.1.tar.gz chdir={{ build }} creates={{ build }}/cmake-3.3.1
      environment: local_env
    - name: Configure cmake
      command: ./configure --prefix={{ base }} chdir={{ build }}/cmake-3.3.1 creates={{ build }}/cmake-3.3.1/CPackConfig.cmake
      environment: local_env
    - name: make cmake
      command: make chdir={{ build }}/cmake-3.3.1 creates={{ build }}/cmake-3.3.1/bin/cmake
      environment: local_env
    - name: Install cmake
      command: make install chdir={{ build }}/cmake-3.3.1 creates={{ base }}/bin/cmake
      environment: local_env

    - name: Get libjpeg
      get_url:
        dest: "{{ build }}/jpegsrc.v6b.tar.gz"
        url: http://sourceforge.net/projects/libjpeg/files/libjpeg/6b/jpegsrc.v6b.tar.gz/download
    - name: Unpack libjpeg
      command: tar -zxf {{ build }}/jpegsrc.v6b.tar.gz chdir={{ build }} creates={{ build }}/jpeg-6b
      environment: local_env
    - name: Configure libjpeg
      command: ./configure --prefix={{ base }} --enable-shared chdir={{ build }}/jpeg-6b creates={{ build }}/jpeg-6b/config.status
      environment: local_env
    - name: Make libjpeg
      command: make chdir={{ build }}/jpeg-6b creates={{build}}/jpeg-6b/cjpeg
      environment: local_env
    - name: Install libjpeg
      command: make install chdir={{ build }}/jpeg-6b creates={{base}}/bin/cjpeg
      environment: local_env
    - name: Install pkg-config file
      template:
        src: "./templates/libjpeg.pc.j2"
        dest: "{{ base }}/lib/pkgconfig/libjpeg.pc"

    - name: Get openjpeg
      get_url:
        dest: "{{ build }}/openjpeg-version.2.1.tar.gz"
        url: https://github.com/uclouvain/openjpeg/archive/version.2.1.tar.gz
    - name: Unpack openjpeg
      command: tar -zxf {{ build }}/openjpeg-version.2.1.tar.gz chdir={{ build }} creates={{ build }}/openjpeg-version.2.1
      environment: local_env
    - name: Configure openjpeg
      command: cmake . -DCMAKE_INSTALL_PREFIX={{ base }} chdir={{ build }}/openjpeg-version.2.1 creates={{ build }}/openjpeg-version.2.1/Makefile
      environment: local_env
    - name: Make openjpeg
      command: make chdir={{ build }}/openjpeg-version.2.1 creates={{build}}/openjpeg-version.2.1/bin/libopenjp2.so
      environment: local_env
    - name: Install openjpeg
      shell: env DESTDIR={{base}} make install chdir={{ build }}/openjpeg-version.2.1 creates={{base}}/lib/libopenjp2.so
      environment: local_env

    - name: Get libtiff
      get_url:
        dest: "{{ build }}/tiff-4.0.4.tar.gz"
        url: ftp://ftp.remotesensing.org/pub/libtiff/tiff-4.0.4.tar.gz
    - name: Unpack libtiff
      command: tar -zxf {{ build }}/tiff-4.0.4.tar.gz chdir={{ build }} creates={{ build }}/tiff-4.0.4
      environment: local_env
    - name: Configure libtiff
      command: ./configure --prefix={{ base }} chdir={{ build }}/tiff-4.0.4 creates={{ build }}/tiff-4.0.4/config.status
      environment: local_env
    - name: Make libtiff
      command: make chdir={{ build }}/tiff-4.0.4 creates={{ build }}/tiff-4.0.4/libtiff/libtiff.la
      environment: local_env
    - name: Install libtiff
      shell: make install chdir={{ build }}/tiff-4.0.4 creates={{ base }}/lib/libtiff.la
      environment: local_env

    ## Openslide
    - name: Get openslide
      git:
        dest: "{{ build }}/openslide"
        repo: "https://github.com/openslide/openslide.git"
      environment: local_env
    - name: Configure openslide
      command: libtoolize chdir={{ build }}/openslide creates={{ build }}/openslide/m4/libtool.m4
      environment: local_env
    - name: Configure openslide
      command: autoreconf -i chdir={{ build }}/openslide creates={{ build }}/openslide/configure
      environment: local_env
    - name: Configure openslide
      command: env PKG_CONFIG_PATH={{ base }}/lib/pkgconfig ./configure --prefix={{ base }} chdir={{ build }}/openslide creates={{ build }}/openslide/config.status
      environment: local_env
